### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by Zoe3542188** [JoranLau/twitterAPI_01#1]
I reviewed your project and I found that the [pics_description.py](https://github.com/JoranLau/twitterAPI_01/blob/master/pics_description.py) and [recon_pic.py](https://github.com/JoranLau/twitterAPI_01/blob/master/recon_pic.py) have same contents. I think it's better to upload them once.

**Comment by JoranLau** [comment]
Okay, I will revise them later.
