### ISSUE TITLE
missing ffmpeg

### ISSUE THREAD

**Issue by Zoe3542188** [JoranLau/twitterAPI_01#3]
The image part works well on my laptop but I didn't find any file about FFMPEG. Are you gonna convert images to video by directly type FFmpeg commands in your command prompt? That's difficult for people to apply your API.

**Comment by Zoe3542188** [comment]
Maybe os.system helps...

**Comment by JoranLau** [comment]
Yeah, it's my fault.  I just forgot to put them on Github.
